//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKulturnoSportskiCentar_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eKulturnoSportskiCentar_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centar uspješno dodan..
        /// </summary>
        internal static string add_centar_succ {
            get {
                return ResourceManager.GetString("add_centar_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o centru uspješno izmjenjeni..
        /// </summary>
        internal static string add_edit_succ {
            get {
                return ResourceManager.GetString("add_edit_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala uspješno dodana.
        /// </summary>
        internal static string add_Sala_succ {
            get {
                return ResourceManager.GetString("add_Sala_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste se oznaćili na odabrani događaj..
        /// </summary>
        internal static string add_usr_evt_succ {
            get {
                return ResourceManager.GetString("add_usr_evt_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik uspješno dodan..
        /// </summary>
        internal static string add_usr_succ {
            get {
                return ResourceManager.GetString("add_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa je obavezano polje..
        /// </summary>
        internal static string Adresa_Required {
            get {
                return ResourceManager.GetString("Adresa_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuspješno brisanje centra..
        /// </summary>
        internal static string Delete_Centar_Faild {
            get {
                return ResourceManager.GetString("Delete_Centar_Faild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o centru uspješno obrisani..
        /// </summary>
        internal static string delete_Centar_succes {
            get {
                return ResourceManager.GetString("delete_Centar_succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite izbrisati centar?.
        /// </summary>
        internal static string delete_msg {
            get {
                return ResourceManager.GetString("delete_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite događaj za koji želite izvršiti akciju..
        /// </summary>
        internal static string dogadjaj_action {
            get {
                return ResourceManager.GetString("dogadjaj_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jednu od ponuđenih opcija..
        /// </summary>
        internal static string DropDown_NotSelected {
            get {
                return ResourceManager.GetString("DropDown_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o korisniku uspjenšno izmjenjeni..
        /// </summary>
        internal static string edit_usr_succ {
            get {
                return ResourceManager.GetString("edit_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je već u upotrebi..
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je u pogrešnom formatu..
        /// </summary>
        internal static string Email_Error {
            get {
                return ResourceManager.GetString("Email_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je obavezno polje..
        /// </summary>
        internal static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška!.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno polje..
        /// </summary>
        internal static string Ime_Required {
            get {
                return ResourceManager.GetString("Ime_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapacitet sjedečih mjesta je obavezno polje..
        /// </summary>
        internal static string Kapcitet_Required {
            get {
                return ResourceManager.GetString("Kapcitet_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno polje..
        /// </summary>
        internal static string KorisnickoIme_Required {
            get {
                return ResourceManager.GetString("KorisnickoIme_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik je već prijaveljen na događaj.
        /// </summary>
        internal static string Korisnik_Dogadjaj_con {
            get {
                return ResourceManager.GetString("Korisnik_Dogadjaj_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešna lozinka..
        /// </summary>
        internal static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime nije pronađeno..
        /// </summary>
        internal static string login_user_err {
            get {
                return ResourceManager.GetString("login_user_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka moram imati više od 8 karaktera..
        /// </summary>
        internal static string Lozinka_Invalid {
            get {
                return ResourceManager.GetString("Lozinka_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezno polje..
        /// </summary>
        internal static string Lozinka_Required {
            get {
                return ResourceManager.GetString("Lozinka_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno!.
        /// </summary>
        internal static string msg_succ {
            get {
                return ResourceManager.GetString("msg_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv je obavezano polje..
        /// </summary>
        internal static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete sliku dimenzija većih od.
        /// </summary>
        internal static string picture_war {
            get {
                return ResourceManager.GetString("picture_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno polje..
        /// </summary>
        internal static string Prezime_Required {
            get {
                return ResourceManager.GetString("Prezime_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona je već u upotrebi!.
        /// </summary>
        internal static string telefon_con {
            get {
                return ResourceManager.GetString("telefon_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto...
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
