//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKulturnoSportskiCentar_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogadjajOcjena
    {
        public int DogadjajOcjenaID { get; set; }
        public Nullable<int> KorisnikID { get; set; }
        public Nullable<int> OcjenaID { get; set; }
        public Nullable<int> DogadjajID { get; set; }
    
        public virtual Dogadjaj Dogadjaj { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Ocjena Ocjena { get; set; }
    }
}
