//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKulturnoSportskiCentar_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogadjajDodatnaOprema
    {
        public int DogadjajDodatnaOpremaID { get; set; }
        public Nullable<int> DogadjajID { get; set; }
        public Nullable<int> DodatnaOpremaID { get; set; }
    
        public virtual DodatnaOprema DodatnaOprema { get; set; }
        public virtual Dogadjaj Dogadjaj { get; set; }
    }
}
