//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKulturnoSportskiCentar_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eKulturnoSportskiCentar_Entities : DbContext
    {
        public eKulturnoSportskiCentar_Entities()
            : base("name=eKulturnoSportskiCentar_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Centar> Centar { get; set; }
        public virtual DbSet<DodatnaOprema> DodatnaOprema { get; set; }
        public virtual DbSet<Dogadjaj> Dogadjaj { get; set; }
        public virtual DbSet<DogadjajDodatnaOprema> DogadjajDodatnaOprema { get; set; }
        public virtual DbSet<DogadjajOcjena> DogadjajOcjena { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<KorisnikDogadjaj> KorisnikDogadjaj { get; set; }
        public virtual DbSet<KorisnikUloga> KorisnikUloga { get; set; }
        public virtual DbSet<Ocjena> Ocjena { get; set; }
        public virtual DbSet<Oprema> Oprema { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Termin> Termin { get; set; }
        public virtual DbSet<Uloga> Uloga { get; set; }
        public virtual DbSet<VrstaDogadjaja> VrstaDogadjaja { get; set; }
    
        public virtual ObjectResult<Centar_Result> esp_Centar_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Centar_Result>("esp_Centar_SelectAll");
        }
    
        public virtual int esp_Centar_Update(Nullable<int> centarID, string naziv, string adresa, string email, string telefon)
        {
            var centarIDParameter = centarID.HasValue ?
                new ObjectParameter("centarID", centarID) :
                new ObjectParameter("centarID", typeof(int));
    
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("adresa", adresa) :
                new ObjectParameter("adresa", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Centar_Update", centarIDParameter, nazivParameter, adresaParameter, emailParameter, telefonParameter);
        }
    
        public virtual ObjectResult<Sala_Result> esp_Sala_GetByCentar(Nullable<int> centarID)
        {
            var centarIDParameter = centarID.HasValue ?
                new ObjectParameter("centarID", centarID) :
                new ObjectParameter("centarID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sala_Result>("esp_Sala_GetByCentar", centarIDParameter);
        }
    
        public virtual int esp_Sala_Update(Nullable<int> salaID, string naziv, Nullable<int> centarID)
        {
            var salaIDParameter = salaID.HasValue ?
                new ObjectParameter("salaID", salaID) :
                new ObjectParameter("salaID", typeof(int));
    
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            var centarIDParameter = centarID.HasValue ?
                new ObjectParameter("centarID", centarID) :
                new ObjectParameter("centarID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Sala_Update", salaIDParameter, nazivParameter, centarIDParameter);
        }
    
        public virtual ObjectResult<Korisnici_Result> esp_Korisnici_SelectByImePrezime(string imePrezime)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Korisnici_Result>("esp_Korisnici_SelectByImePrezime", imePrezimeParameter);
        }
    
        public virtual int esp_KorisniciUloge_Delete(Nullable<int> korisnikID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("korisnikID", korisnikID) :
                new ObjectParameter("korisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_KorisniciUloge_Delete", korisnikIDParameter);
        }
    
        public virtual int esp_KorisniciUloge_Insert(Nullable<int> korisnikID, Nullable<int> ulogaID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("KorisnikID", korisnikID) :
                new ObjectParameter("KorisnikID", typeof(int));
    
            var ulogaIDParameter = ulogaID.HasValue ?
                new ObjectParameter("UlogaID", ulogaID) :
                new ObjectParameter("UlogaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_KorisniciUloge_Insert", korisnikIDParameter, ulogaIDParameter);
        }
    
        public virtual ObjectResult<Korisnici_Result1> esp_Korisnik_SelectById(Nullable<int> korisnikID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("korisnikID", korisnikID) :
                new ObjectParameter("korisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Korisnici_Result1>("esp_Korisnik_SelectById", korisnikIDParameter);
        }
    
        public virtual ObjectResult<Korisnici_Result1> esp_Korisnik_SelectByUsername(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Korisnici_Result1>("esp_Korisnik_SelectByUsername", usernameParameter);
        }
    
        public virtual int esp_Korisnik_Update(Nullable<int> korisnikID, string ime, string prezime, string email, string telefon, string korisnickoIme, string lozinkaSalt, string lozinkaHash, Nullable<bool> status)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("KorisnikID", korisnikID) :
                new ObjectParameter("KorisnikID", typeof(int));
    
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Korisnik_Update", korisnikIDParameter, imeParameter, prezimeParameter, emailParameter, telefonParameter, korisnickoImeParameter, lozinkaSaltParameter, lozinkaHashParameter, statusParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> esp_Korisnici_Insert(string ime, string prezime, string telefon, string email, string korisnickoIme, string lozinkaSalt, string lozinkaHash)
        {
            var imeParameter = ime != null ?
                new ObjectParameter("ime", ime) :
                new ObjectParameter("ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("prezime", prezime) :
                new ObjectParameter("prezime", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("korisnickoIme", korisnickoIme) :
                new ObjectParameter("korisnickoIme", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("lozinkaSalt", lozinkaSalt) :
                new ObjectParameter("lozinkaSalt", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("lozinkaHash", lozinkaHash) :
                new ObjectParameter("lozinkaHash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("esp_Korisnici_Insert", imeParameter, prezimeParameter, telefonParameter, emailParameter, korisnickoImeParameter, lozinkaSaltParameter, lozinkaHashParameter);
        }
    
        public virtual ObjectResult<KorisniciUloge_Result> esp_KorisniciUloge_GetByUserID(Nullable<int> korisnikID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("korisnikID", korisnikID) :
                new ObjectParameter("korisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KorisniciUloge_Result>("esp_KorisniciUloge_GetByUserID", korisnikIDParameter);
        }
    
        public virtual int esp_Termin_Change(Nullable<int> terminID, Nullable<int> rezervisan)
        {
            var terminIDParameter = terminID.HasValue ?
                new ObjectParameter("terminID", terminID) :
                new ObjectParameter("terminID", typeof(int));
    
            var rezervisanParameter = rezervisan.HasValue ?
                new ObjectParameter("rezervisan", rezervisan) :
                new ObjectParameter("rezervisan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Termin_Change", terminIDParameter, rezervisanParameter);
        }
    
        public virtual ObjectResult<Termin_Result> esp_Termin_Select(Nullable<System.DateTime> datum, Nullable<int> salaID)
        {
            var datumParameter = datum.HasValue ?
                new ObjectParameter("datum", datum) :
                new ObjectParameter("datum", typeof(System.DateTime));
    
            var salaIDParameter = salaID.HasValue ?
                new ObjectParameter("salaID", salaID) :
                new ObjectParameter("salaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Termin_Result>("esp_Termin_Select", datumParameter, salaIDParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> esp_GetZadnjiDatumTermina_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("esp_GetZadnjiDatumTermina_Select");
        }
    
        public virtual int esp_DogadjajDodatnaOprema_Insert(Nullable<int> dogadjajID, Nullable<int> dodatnaOpremaID)
        {
            var dogadjajIDParameter = dogadjajID.HasValue ?
                new ObjectParameter("dogadjajID", dogadjajID) :
                new ObjectParameter("dogadjajID", typeof(int));
    
            var dodatnaOpremaIDParameter = dodatnaOpremaID.HasValue ?
                new ObjectParameter("dodatnaOpremaID", dodatnaOpremaID) :
                new ObjectParameter("dodatnaOpremaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_DogadjajDodatnaOprema_Insert", dogadjajIDParameter, dodatnaOpremaIDParameter);
        }
    
        public virtual ObjectResult<MojiDogadjaji_Result> esp_MojiDogadjaji_SelectByKorisnik(Nullable<int> korisniID)
        {
            var korisniIDParameter = korisniID.HasValue ?
                new ObjectParameter("korisniID", korisniID) :
                new ObjectParameter("korisniID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MojiDogadjaji_Result>("esp_MojiDogadjaji_SelectByKorisnik", korisniIDParameter);
        }
    
        public virtual ObjectResult<Dogadjaji_Result> esp_Dogadjaj_JavniDogadjaji_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dogadjaji_Result>("esp_Dogadjaj_JavniDogadjaji_Select");
        }
    
        public virtual ObjectResult<Lista_Result> esp_Dogadjaj_SelectListaPrisutnih(Nullable<int> dogadjajID)
        {
            var dogadjajIDParameter = dogadjajID.HasValue ?
                new ObjectParameter("dogadjajID", dogadjajID) :
                new ObjectParameter("dogadjajID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lista_Result>("esp_Dogadjaj_SelectListaPrisutnih", dogadjajIDParameter);
        }
    
        public virtual ObjectResult<DogadjajiZaAdministraciju_Result> esp_DogadjajiZaAdministraciju_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DogadjajiZaAdministraciju_Result>("esp_DogadjajiZaAdministraciju_Select");
        }
    
        public virtual ObjectResult<Oprema_Result> esp_Oprema_Select(Nullable<int> salaId)
        {
            var salaIdParameter = salaId.HasValue ?
                new ObjectParameter("salaId", salaId) :
                new ObjectParameter("salaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Oprema_Result>("esp_Oprema_Select", salaIdParameter);
        }
    
        public virtual int esp_Oprema_Update(Nullable<int> opremaId, string naziv, Nullable<int> kolicina, Nullable<int> salaId, byte[] slika, byte[] slikaThumb)
        {
            var opremaIdParameter = opremaId.HasValue ?
                new ObjectParameter("opremaId", opremaId) :
                new ObjectParameter("opremaId", typeof(int));
    
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            var kolicinaParameter = kolicina.HasValue ?
                new ObjectParameter("kolicina", kolicina) :
                new ObjectParameter("kolicina", typeof(int));
    
            var salaIdParameter = salaId.HasValue ?
                new ObjectParameter("salaId", salaId) :
                new ObjectParameter("salaId", typeof(int));
    
            var slikaParameter = slika != null ?
                new ObjectParameter("slika", slika) :
                new ObjectParameter("slika", typeof(byte[]));
    
            var slikaThumbParameter = slikaThumb != null ?
                new ObjectParameter("slikaThumb", slikaThumb) :
                new ObjectParameter("slikaThumb", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Oprema_Update", opremaIdParameter, nazivParameter, kolicinaParameter, salaIdParameter, slikaParameter, slikaThumbParameter);
        }
    
        public virtual ObjectResult<DogadjajiZaPrisustvovati_Result> esp_DogadjajiZaPrisustvovati_SelectByKorisnik(Nullable<int> korisnikID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("korisnikID", korisnikID) :
                new ObjectParameter("korisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DogadjajiZaPrisustvovati_Result>("esp_DogadjajiZaPrisustvovati_SelectByKorisnik", korisnikIDParameter);
        }
    
        public virtual ObjectResult<Detalji_Dogadjaja_Result> esp_Dogadjaj_Detalji(Nullable<int> dogadjajID)
        {
            var dogadjajIDParameter = dogadjajID.HasValue ?
                new ObjectParameter("dogadjajID", dogadjajID) :
                new ObjectParameter("dogadjajID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Detalji_Dogadjaja_Result>("esp_Dogadjaj_Detalji", dogadjajIDParameter);
        }
    
        public virtual int esp_Dogadjaj_Update(Nullable<int> dogadjajID, Nullable<int> odobri, Nullable<int> aktivan)
        {
            var dogadjajIDParameter = dogadjajID.HasValue ?
                new ObjectParameter("DogadjajID", dogadjajID) :
                new ObjectParameter("DogadjajID", typeof(int));
    
            var odobriParameter = odobri.HasValue ?
                new ObjectParameter("odobri", odobri) :
                new ObjectParameter("odobri", typeof(int));
    
            var aktivanParameter = aktivan.HasValue ?
                new ObjectParameter("aktivan", aktivan) :
                new ObjectParameter("aktivan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Dogadjaj_Update", dogadjajIDParameter, odobriParameter, aktivanParameter);
        }
    
        public virtual ObjectResult<Dogadjaj_Detalji_Result> esp_Dogadjaj_Detalji_Filter(Nullable<System.DateTime> pocetniDatum, Nullable<System.DateTime> krajnjiDatum)
        {
            var pocetniDatumParameter = pocetniDatum.HasValue ?
                new ObjectParameter("pocetniDatum", pocetniDatum) :
                new ObjectParameter("pocetniDatum", typeof(System.DateTime));
    
            var krajnjiDatumParameter = krajnjiDatum.HasValue ?
                new ObjectParameter("KrajnjiDatum", krajnjiDatum) :
                new ObjectParameter("KrajnjiDatum", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dogadjaj_Detalji_Result>("esp_Dogadjaj_Detalji_Filter", pocetniDatumParameter, krajnjiDatumParameter);
        }
    
        public virtual ObjectResult<Dogadjaji_Result> esp_JavniDogadjaj_SelectByDogadjajID(Nullable<int> dogadjajID)
        {
            var dogadjajIDParameter = dogadjajID.HasValue ?
                new ObjectParameter("dogadjajID", dogadjajID) :
                new ObjectParameter("dogadjajID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dogadjaji_Result>("esp_JavniDogadjaj_SelectByDogadjajID", dogadjajIDParameter);
        }
    }
}
