//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKulturnoSportskiCentar_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oprema
    {
        public int OpremaID { get; set; }
        public string Naziv { get; set; }
        public int Kolicina { get; set; }
        public int SalaID { get; set; }
        public byte[] Slika { get; set; }
        public byte[] SlikaThumb { get; set; }
    
        public virtual Sala Sala { get; set; }
    }
}
