//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKulturnoSportskiCentar_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termin()
        {
            this.Dogadjaj = new HashSet<Dogadjaj>();
        }
    
        public int TerminID { get; set; }
        public System.DateTime Datum { get; set; }
        public System.TimeSpan Pocetak { get; set; }
        public System.TimeSpan Kraj { get; set; }
        public bool Rezervisan { get; set; }
        public Nullable<int> SalaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dogadjaj> Dogadjaj { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
